# -*- coding: utf-8 -*-
"""Cat_Dog_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Pp1tLqD-BAOizJpozevanIaeJVv5Pjg
"""

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten

cla = Sequential()

cla.add(Convolution2D(32,3,3, input_shape = (64, 64, 3), activation='relu'))

cla.add(MaxPooling2D(pool_size=(2,2)))

cla.add(Flatten())

cla.add(Dense(units=128, activation='relu'))
cla.add(Dense(units=1, activation='sigmoid'))

cla.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255,
        shear_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True)
training_set = train_datagen.flow_from_directory(
        '/content/drive/MyDrive/ds/train',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')

test_datagen = ImageDataGenerator(rescale=1./255)
test_set = test_datagen.flow_from_directory(
        '/content/drive/MyDrive/ds/test',
        target_size=(64, 64),
        batch_size=32,
        class_mode='binary')

cla.fit(
        training_set,
        epochs=25,
        validation_data=test_set,
        )

import numpy as np
from keras.preprocessing import image
test_image = image.load_img('/content/drive/MyDrive/ds/train/cats/cat.2040.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cla.predict(test_image)
training_set.class_indices
if result[0][0] == 1:
  prediction = 'dog'
else:
  prediction = 'cat'

print(prediction)